Coverage improvement test is commented out
Sur le fichier test.yml, l'étape "Fail if coverage has not improved" est maintenant désactivé. Normalement, les tests devraient réussirent même si le coverage ne change pas.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,13 +26,13 @@ jobs:
         coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
         echo "COVERAGE=$coverage" >> $GITHUB_ENV
 
-    - name: Fail if coverage has not improved.
-      run: |
-        coverage=$COVERAGE
-        threshold=24.46
-        if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
-          echo "Coverage is not improved."
-          exit 1
-        else
-          echo "New coverage: $coverage%. Coverage is improved!"
-        fi
+    #- name: Fail if coverage has not improved.
+    #  run: |
+    #    coverage=$COVERAGE
+    #    threshold=24.46
+    #    if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
+    #      echo "Coverage is not improved."
+    #      exit 1
+    #    else
+    #      echo "New coverage: $coverage%. Coverage is improved!"
+    #    fi
